### ISSUE TITLE
[Reformat] Formatting at numeric strings is introducing changes in the rendered document

### ISSUE THREAD

**Issue by daeh** [jeffa5/typstfmt#40] opened 2024-09-11 03:46 UTC
**To Reproduce**

Code snippet:

```typst
  Houlihan, S. D., Kleiman-Weiner, M., Hewitt, L. B., Tenenbaum, J. B., & Saxe, R. (2023). Emotion prediction as computation over a generative theory of mind. #emph[Philosophical Transactions of the Royal Society A: Mathematical, Physical and Engineering Sciences], _381_(2251), 20220047. 
  #bodylink("https://doi.org/10.1098/rsta.2022.0047")
```

**Additional context**

The formatter is introducing line breaks in the code that are rendering in the typeset document.

For instance, the code above is formatted to:

```typst
  Houlihan, S. D., Kleiman-Weiner, M., Hewitt, L. B., Tenenbaum, J. B., & Saxe, R. (2023). Emotion prediction as
  computation over a generative theory of mind. #emph[Philosophical Transactions of the Royal Society A: Mathematical, Physical and Engineering Sciences], _381_(2251),
  20220047.
  #bodylink("https://doi.org/10.1098/rsta.2022.0047")
```

Typst interprets the numeric string `20220047.` as non-text, and forces new lines before and after it

<img width="959" alt="image" src="https://github.com/user-attachments/assets/0c29c902-7b0e-494a-980d-78638538cbca">

Ideally the formatter should be extremely conservative about code reformats that could change document rendering. 

This is the output of the first code block (pre-format). Without the formatter (and the linebreak it introduces before `20220047`), the code renders correctly.:

<img width="815" alt="image" src="https://github.com/user-attachments/assets/f64c9612-61ff-4e6f-8164-f60d790bb39d">

Thanks!

**Comment by jeffa5** [comment] 2024-10-12 17:08
Closing as unable to reproduce, can reopen if a `test_snippet` is provided.

**Closed by jeffa5** 2024-10-12 17:08 UTC
Labels: bug, reformat
